### ISSUE TITLE
您好，这里面是没有enframe函数的吗 

### ISSUE THREAD

**Issue by shijian-yang** [MorrisXu-Driving/Speech-Augmentation-and-Endpoint-Detection#1]
运行程序的时候发现报错没有enframe函数，请问是不是忘记上传了

**Comment by MorrisXu-Driving** [comment]
不好意思，我在readme中忘记提到这一点。这个脚本需要MATLAB Voicebox 工具箱。具体的安装步骤可参考：https://blog.csdn.net/jojozhangju/article/details/19337165
里面自带enframe()函数和其他必要的函数。

**Comment by shijian-yang** [comment]
好的好的，谢谢啦。请问这个工具箱有没有版本要求呀发自我的华为手机-------- 原始邮件 --------发件人： Morris Xu <notifications@github.com>日期： 2020年10月14日周三 10:04收件人： MorrisXu-Driving/Speech-Augmentation-and-Endpoint-Detection <Speech-Augmentation-and-Endpoint-Detection@noreply.github.com>抄送： YSJ <Yangshijian0201@163.com>, Author <author@noreply.github.com>主    题： Re: [MorrisXu-Driving/Speech-Augmentation-and-Endpoint-Detection] 您好，这里面是没有enframe函数的吗  (#1)

不好意思，我在readme中忘记提到这一点。这个脚本需要MATLAB Voicebox 工具箱。具体的安装步骤可参考https://blog.csdn.net/jojozhangju/article/details/19337165。里面自带enframe()函数和其他必要的函数。

**Comment by MorrisXu-Driving** [comment]
http://www.ee.ic.ac.uk/hp/staff/dmb/voicebox/voicebox.html
这个是他们官网，看起来没有重大更新，MATLAB我用的2016b的版本，如果有其他bug问题直接在这问。

**Comment by MorrisXu-Driving** [comment]
This problem is easy and is well addressed.
